sudo: required

services: docker

before_install:
  - docker-compose up --build -d
dist: jammy

script:
  - docker-compose exec -e 'RAILS_ENV=test' web rails db:create
  - docker-compose exec -e 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec -e 'RAILS_ENV=test' web rails test
